sudo: false
language: python
os: linux
dist: xenial

python:
    - 3.6
    - 3.7
    - 3.8
    - pypy3.6-7.1.1

install:
    - pip install --upgrade pip
    - pip install innerscope coverage pytest
    - pip install -e .

script:
    - coverage run --branch -m pytest --doctest-modules
    - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]] ; then pip install flake8 black ; fi
    - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]] ; then flake8 ; fi
    - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]] ; then black innertube --check --diff ; fi

after_success:
    - coverage report --show-missing
    - pip install coveralls
    - coveralls

deploy:
    provider: pypi
    skip_existing: true
    on:
        tags: true
    user: __token__
    password:
        secure: "kft01q2eU0tQIMGB9MNUZI7dJZgoBnYFMjfy6v4n+JlIxI2dex0L8gcFcOoiRfUtVK5TAGSG1wXog8Xj5mtWAhpL2+r6pQNR8+gq+GP9pMziMsRtFGif+n3OivB/kp4YaO4xmEKgiopt+E/kD/IHTNsKSJf/wNwVTe0/InEm4ZnVFuMtG87ODV9bF7/0hQt2q5nRHHj0AF12Acb+Q6rqLQFMp4DwXn5EUVYIXI/MUREQvkGqc5Y1MD7FPDhOpxFeHs4Z0/bQV4Jsimgk6rGhJJCYCu12CQJ4awhPc0NIAKqsiYspoeydZ8wDLiCgBtlt7sEIwE/glz/WHQzKNoMHXLE28n1VEf6DZhl4SclVadl/wCfu1k3Y4ufYEYKrPkrrds4fXg+UuyV4bCJuIyCOXIpgYrix20XJtOWg3WoNEHIDAFTZpxY44imfJDRqufGBzP9cQUdLAxQKjN0B6GCXhjYpRAM9wgF1KE/N9zbFbK/PH7SCUFo56Zlf8HxiqcqULNq2GYwe9r9QfYtz368jn6eIimJusNdBLy9H3Zfp4zZaWld6w8z9dMA6oid8Ipi0QMXnZp9dWFzDfGpZq+B4mktdzh+oRCx4qT811+48B0Wg+vppd0CC5o1lJibjNhna/b/20/t0Z7rDSGAqMIQ8lBkJPr4N0uF6sFZcNKZw4jE="
    distributions: sdist bdist_wheel

notifications:
    email: false
